### ISSUE TITLE
Add Contributors.md File

### ISSUE THREAD

**Issue by muthuannamalai12** [commudle/commudle-ng#102]
Hai,
I would like to add Contributors.md file in your project in the form of a table and display a link to it in README.md

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign me this issue.

**Comment by Ashwin-op** [comment]
If needed this can be used -- https://allcontributors.org/

**Comment by arpansac** [comment]
Let's do this @muthuannamalai12

**Comment by muthuannamalai12** [comment]
> Let's do this @muthuannamalai12

I have created a pull request. Kindly review it and add DWOC label to it
