### ISSUE TITLE
CODE OF CONDUCT FILE 

### ISSUE THREAD

**Issue by akrish4** [commudle/commudle-ng#104]
Hi @arpansac 
I would like to contribu4to this repository by creating a code of conduct file which is messing in this repository 

Kindly assign me this issue

**Comment by Ashwin-op** [comment]
Please don't create multiple issues. This is already being addressed at #99 and #100

**Comment by akrish4** [comment]
@Ashwin-op  let me know if there is any other documentation needs to be worked on , I would be glad to do it 
@arpansac
