### ISSUE TITLE
Integrate Welcome Bot

### ISSUE THREAD

**Issue by tharunc** [commudle/commudle-ng#106]
Hello there,
         I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time as a part of DWOC. Please assign me this issue. For reference, kindly check out: https://github.com/apps/welcome
THANK YOU

**Comment by arpansac** [comment]
Sounds cool, can you please post all the messages we will be having here? I'd love to customize them a little.

**Comment by tharunc** [comment]
newIssueWelcomeComment: >
  Hello there!👋 Welcome to the project!🚀⚡
  
  
  Thank you and congrats🎉 for opening your very first issue in this project.
  Please adhere to our [Code of Conduct]

newPRWelcomeComment: >
  Hello there!👋 Welcome to the project!💖
  
  
  Thank you and congrats🎉 for opening your first pull request.✨ 
  Please adhere to our [Code of Conduct]. We will get back to you as soon as we can 😄.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user

firstPRMergeComment: >
  Congrats on merging your first pull request! 🎉 All the best for your amazing open source journey ahead 🚀

**Comment by arpansac** [comment]
> newIssueWelcomeComment: >
> Hello there!👋 Welcome to the project!🚀⚡
> 
> Thank you and congrats🎉 for opening your very first issue in this project.
> Please adhere to our [Code of Conduct]
> 
> newPRWelcomeComment: >
> Hello there!👋 Welcome to the project!💖
> 
> Thank you and congrats🎉 for opening your first pull request.✨
> Please adhere to our [Code of Conduct]. We will get back to you as soon as we can 😄.
> 
> # Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
> # Comment to be posted to on pull requests merged by a first time user
> firstPRMergeComment: >
> Congrats on merging your first pull request! 🎉 All the best for your amazing open source journey ahead 🚀

Looks good, let's please replace 'the project' everywhere with 'Commudle'

**Comment by arpansac** [comment]
> > newIssueWelcomeComment: >
> > Hello there!👋 Welcome to the project!🚀⚡
> > Thank you and congrats🎉 for opening your very first issue in this project.
> > Please adhere to our [Code of Conduct]
> > newPRWelcomeComment: >
> > Hello there!👋 Welcome to the project!💖
> > Thank you and congrats🎉 for opening your first pull request.✨
> > Please adhere to our [Code of Conduct]. We will get back to you as soon as we can 😄.
> > # Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
> > # Comment to be posted to on pull requests merged by a first time user
> > firstPRMergeComment: >
> > Congrats on merging your first pull request! 🎉 All the best for your amazing open source journey ahead 🚀
> 
> Looks good, let's please replace 'the project' everywhere with 'Commudle'

@tharunc any progress on this?

**Comment by arpansac** [comment]
closed by #112 
Thank You @tharunc :)
