### ISSUE TITLE
Create Issue Template

### ISSUE THREAD

**Issue by muthuannamalai12** [commudle/commudle-ng#107]
Hai,
I would love to add an issue template for your repository. This template would have four issues namely bug, documentation, feature, proposal .

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign it to me

**Comment by arpansac** [comment]
Hey! Can you please share some sample templates links?

**Comment by muthuannamalai12** [comment]
![Template 1](https://user-images.githubusercontent.com/64524822/103920816-bc5a0780-5137-11eb-8a08-734ec063231e.png)
![Template 2](https://user-images.githubusercontent.com/64524822/103920828-bfed8e80-5137-11eb-92c9-76701e19489b.png)
![Template](https://user-images.githubusercontent.com/64524822/103920838-c24fe880-5137-11eb-90ca-0365c8ee1b6f.png)

**Comment by muthuannamalai12** [comment]
![Template 1](https://user-images.githubusercontent.com/64524822/103920879-cda31400-5137-11eb-8902-5bfb31c7fe8f.png)

**Comment by muthuannamalai12** [comment]
![Template 2](https://user-images.githubusercontent.com/64524822/103920908-d5fb4f00-5137-11eb-89e5-d67b8f1b4d5d.png)

**Comment by muthuannamalai12** [comment]
![Template](https://user-images.githubusercontent.com/64524822/103920918-dd225d00-5137-11eb-91c2-fc25cc8498e1.png)

**Comment by muthuannamalai12** [comment]
![Template](https://user-images.githubusercontent.com/64524822/103921003-f6c3a480-5137-11eb-9311-7432263ba521.png)

**Comment by arpansac** [comment]
Done, let's do this

**Comment by muthuannamalai12** [comment]
I have created a pull request. Kindly review it

**Comment by arpansac** [comment]
> I have created a pull request. Kindly review it

Reviewed, merging soon. Thanks a ton

**Comment by muthuannamalai12** [comment]
> > I have created a pull request. Kindly review it
> 
> Reviewed, merging soon. Thanks a ton

Thank you

**Comment by muthuannamalai12** [comment]
I have reverted the PR I made. Kindly review it again @arpansac . Sorry for inconvenience

**Comment by arpansac** [comment]
> I have reverted the PR I made. Kindly review it again @arpansac . Sorry for inconvenience

I've merged the revert. Thanks!
