### ISSUE TITLE
PR TEMPLATE

### ISSUE THREAD

**Issue by muthuannamalai12** [commudle/commudle-ng#114]
## 🚀 Feature
I can add a pr template , which will have few checklists and options like uploading screenshots and describing about the pr etc , which will give better understanding of pr for the maintainer
(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/commudle/commudle-ng/blob/development/CONTRIBUTING.md)?
Yes
(Write your answer here.)

## Motivation
Self Motivation
(Please outline the motivation for the proposal.)

## Pitch
This is a great feature like issue template in this project , this will give a better idea about the pr and also make the work easy
(Please explain why this feature should be implemented and how it would be used.)

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign me this issue.

**Comment by muthuannamalai12** [comment]
It would look like the photo mentioned below
![Pull Request Template](https://user-images.githubusercontent.com/64524822/104718068-4f0a3000-5750-11eb-9b2e-11e5f07f6815.png)

**Comment by arpansac** [comment]
Hey @muthuannamalai12 
I think it's too early to create a PR template, more so because we already have templates for issues right now, let's see how that works
