### ISSUE TITLE
Update to Nebular 7

### ISSUE THREAD

**Issue by Ashwin-op** [commudle/commudle-ng#116]
## 🚀 Feature

Nebular 7.0.0 just released and let's update!

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/commudle/commudle-ng/blob/development/CONTRIBUTING.md)?

Yes

## Motivation

Nebular just got a new version (v7) and let's update our application as well

## Pitch

Things to do:

- Update to Nebular 7 (latest version)
- Test if there are any breaking changes in the application

**Comment by arpansac** [comment]
Sure, let's do this!

**Comment by arpansac** [comment]
Done already!
