### ISSUE TITLE
Implement Nebular's Tag Component

### ISSUE THREAD

**Issue by Ashwin-op** [commudle/commudle-ng#117]
## 🚀 Feature

Right now, there is a separate self-written badge component. Since Nebular got an inbuilt tag component, we can update to using that.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/commudle/commudle-ng/blob/development/CONTRIBUTING.md)?

Yes

## Motivation

The motivation for this issue is that Nebular has got its own Tag component.

## Pitch

It's easier to manage since the Nebular library now supports an inbuilt component. This has to be implemented both in the event viewing pages and the event creation pages.

As an extension, since there is also a TagInput component in Nebular, we can use that to get badge inputs in event creation pages.

**Comment by arpansac** [comment]
Actually that tag component has been intentionally created because Nebular's tag component gives very limited functionality :D
