### ISSUE TITLE
Contributors Images

### ISSUE THREAD

**Issue by Swastik1710** [commudle/commudle-ng#120]
## 📚 Documentation

Adding Contributors image in the readme file .

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/commudle/commudle-ng/blob/development/CONTRIBUTING.md)?

Yes , I've read the contributing guidelines .

**Comment by Swastik1710** [comment]
Hey , can I work on this issue ?

**Comment by arpansac** [comment]
I think you missed the readme before the contribution guidelines. We already have this.
