### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by arpansac** [commudle/commudle-ng#13]
There is already a component which allows updating the profile when a user is filling a form for an event. 

- Create an edit profile page using that component
- Create a profile page which is publicly visible

**Comment by arpansac** [comment]
I've created a basic profile update page, need a display page now

**Comment by arpansac** [comment]
I've added a url for updating the profile info, it shows incomplete in case the values of required fields are missing.

**Comment by arpansac** [comment]
solved with #98

**Comment by knightmate** [comment]
is this issue available?

**Comment by arpansac** [comment]
> is this issue available?

Oopsie, somehow this didn't get closed. I've already completed it.
