### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by arpansac** [commudle/commudle-ng#14]
Integrate a sitemap generator, or just create a sitemap

**Comment by umangbarthwal** [comment]
@arpansac sir, I want to work with sitemap issue. I found this open source [https://www.npmjs.com/package/sitemap-generator](url) sitemap generator, written in JS and working env is node. It generates XML file. I am thinking to add this as a helper tool outside the main project folder.

**Comment by arpansac** [comment]
Go ahead, try the library, if it works fine, we'll use it!
Also try this one: https://chrome.google.com/webstore/detail/sitemap-generator/hcnjemngcihnhncobgdgkkfkhmleapah?hl=en

Should I then assign this issue to you?

**Comment by umangbarthwal** [comment]
I have already tried the chrome plugin that you've mentioned. And both of them yielding the same result. But I have doubt regarding the results, whether it is correct or not ? The generated sitemap contains only one url, but it supposed to map all the pages.

<img width="592" alt="sitemap" src="https://user-images.githubusercontent.com/40247717/83884919-39b53800-a763-11ea-8b57-34eda388c8fc.png">
Would you confirm it ? Or I have mistaken somewhere ?
( I am using this url https://commudle.com for generating site-map.)

**Comment by Ashwin-op** [comment]
Even I tried, since there are no links in the main page and other admin pages require login the programs aren't creating sitemaps that we want. I'm not sure how to proceed in this aspect

**Comment by arpansac** [comment]
Do you think this because we're using Angular?

**Comment by Ashwin-op** [comment]
Not because of angular, I think this will be the case wherever there is lesser number of public routes.

**Comment by arpansac** [comment]
Any solution till now?

**Comment by Ashwin-op** [comment]
Writing the XML manually is one option or collect the sub URLs and write a program to generate it is another option.

One such example
```node
function generate_xml_sitemap() {
  // this is the source of the URLs on the site, in this case we use a simple array, actually it could come from the database
  var urls = ['about.html', 'javascript.html', 'css.html'];
  // the root of your website - the protocol and the domain name with a trailing slash
  var root_path = 'http://www.example.com/';
  // XML sitemap generation starts here
  var priority = 0.5;
  var freq = 'monthly';
  var xml = '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';
  for (var i in urls) {
    xml += '<url>';
    xml += '<loc>'+ root_path + urls[i] + '</loc>';
    xml += '<changefreq>'+ freq +'</changefreq>';
    xml += '<priority>'+ priority +'</priority>';
    xml += '</url>';
    i++;
  }
  xml += '</urlset>';
  return xml;
}
```

**Comment by arpansac** [comment]
@Ashwin-op 
Majorly we'll be needing paths for 
- All the communities
- Their events
- Sessions in these events

So it appears that we'll be looking at crawling our own website for generating a sitemap.

One solution is that we cite a couple of API's (example, of communities and all it's events) and then loop over them to generate the sitemap for at least them.

What do you think?

**Comment by Ashwin-op** [comment]
Yes, we can create a sitemap containing links of communities and its events using APIs. Are the sessions in these events publicly accessible without logging in? If not, is it advisable to include those links in the sitemap?

**Comment by arpansac** [comment]
Yup, all the communities and events have a public link available

**Comment by Sloth-Panda** [comment]
Hey, Can I Take this issue?

**Comment by arpansac** [comment]
Hey @Sloth-Panda actually a PR already got created by @Ashwin-op even before I assigned this one to him :)
