### ISSUE TITLE
Fix SSR with Angular Universal

### ISSUE THREAD

**Issue by arpansac** [commudle/commudle-ng#16]
There is an error while Server Side Rendering with Angular Universal. The ActionCable js library probably. Need help fixing it

**Comment by amanintech** [comment]
Isnt our application SPA with CSR ?

**Comment by arpansac** [comment]
Yup!

**Comment by arpansac** [comment]
Code part is done, just testing it, will deploy it as soon as possible in SSR mode :D

**Comment by arpansac** [comment]
The error was that the app was connecting to the socket before the page was delivered to the browser. Angular has this inbuilt option isPlatformBrowser which is very amazing.

Also, setInterval causes the app to hang before being delivered to the browser, so I removed it, or put the browser platform check on it too
