### ISSUE TITLE
Add cookie consent message

### ISSUE THREAD

**Issue by arpansac** [commudle/commudle-ng#17]
Simple, create a component for cookie consent.

Should be displayed once per session. Use local storage to remember not asking the user again. 

In the next step we will link this to an API to store the consent per user (if we need to)

**Comment by jrstrayhorn** [comment]
I would like to work on this one!

**Comment by arpansac** [comment]
@jrstrayhorn thanks a lot. Let's do this, assigning this issue to you.
Would be great if you can just put a rough timeline we're looking at!

**Comment by jrstrayhorn** [comment]
Hi @arpansac! I plan to start working on it today and have a PR in for it over next 24 to 48 hrs.

Going to take the approach that patreon.com uses for their cookie consent (see screen shot below), between top nav and main content for commudle site - that work for you?

![patreon-cookie-consent](https://user-images.githubusercontent.com/21061492/95584221-52807380-0a0b-11eb-836a-09b2c45fb36b.png)

**Comment by arpansac** [comment]
Sounds cool @jrstrayhorn 
As for the position of the consent, we're using [Nebular](https://akveo.github.io/nebular/docs/components/components-overview) library

Probably using the window component might make it easier for you. Preferred position is any place at the bottom :)

**Comment by arpansac** [comment]
Any updates @jrstrayhorn ?

**Comment by jrstrayhorn** [comment]
Hi! @arpansac - I left you questions and updated comments on the pull request - https://github.com/commudle/commudle-ng/pull/84 a few days ago 😊

**Comment by arpansac** [comment]
Oops, somehow didn't get a notification mail :P

Let me merge and test it, if everything's fine, it'll be live in the next 12 hours 👍

**Comment by arpansac** [comment]
I guess 1 change was pending, I was just figuring it out myself. Your code will be live in 1 hour :D
