### ISSUE TITLE
Change kommunity to community everywhere needed

### ISSUE THREAD

**Issue by arpansac** [commudle/commudle-ng#19]
Initially when I began writing code, I'd named it Kommunities. Then, we moved to the name 'Commudle'. So, although I've tried to keep it 'community' everywhere in the front end code, but still there are some points left. 

If you choose to do this, then me (@arpansac ) and you will be working in coordination to get this done because it'll require renaming of the table on the server side too.

**Comment by harsh26apr** [comment]
I want to take this issue.

**Comment by arpansac** [comment]
Sure! Though the work will be more for me, but let's do this!

**Comment by arpansac** [comment]
**ROUTINECHECK**
@harsh26apr when shall we begin?

**Comment by harsh26apr** [comment]
@arpansac Let us begin on July 5.

**Comment by Sloth-Panda** [comment]
Hey I can take a look into this. Let me know.

**Comment by arpansac** [comment]
Hey @Sloth-Panda we've postponed this for now. Requires some major testing at the server side.
