### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by arpansac** [commudle/commudle-ng#24]
Make the app into PWA. 
Do discuss which links we want to cache in the service worker.

**Comment by amanintech** [comment]
Can I have It ?

**Comment by arpansac** [comment]
@amanintech yup. Assigning this to you

**Comment by arpansac** [comment]
**ROUTINECHECK**
@amanintech any progress?

**Comment by amanintech** [comment]
Maybe by this weekend @arpansac

**Comment by arpansac** [comment]
Merging this in the coming week, just completing a new feature...!

**Comment by amanintech** [comment]
This still hasn't been merged yet and I think now it will have conflicts. Do you want me to create another PR?

**Comment by arpansac** [comment]
It'd be great if you can, this got backlogged because of the SSR thing,
wrapping up the code for version 1.0 and will come to this PR just next to
it. Mostly 1st week of September should be it.
Would be a big help if you can resolve the conflicts and update the PR :)

**Comment by amanintech** [comment]
Sure no worries

**Comment by arpansac** [comment]
Reviewed once, will be merged early next week! :)

**Comment by arpansac** [comment]
Tested and deployed with: #80
