### ISSUE TITLE
Convert *ngIf to *ngSwitch

### ISSUE THREAD

**Issue by arpansac** [commudle/commudle-ng#37]
Initially ngswitch wasn't required, but then the codebase grew fast.

Find all the places where *ngIf is used multiple times for the a different HTML element being displayed based on different values of a certain condition. Implement ngSwitch there and test it!

**Comment by saksham93** [comment]
Hi, I wish to work on this issue. Thank you.

**Comment by arpansac** [comment]
Great @saksham93 
Let's begin. Do go through the files and give a rough estimate of the days in which you'll be completing it.
Assigning this to you.

**Comment by arpansac** [comment]
This issue is free to be taken now

**Comment by arpansac** [comment]
Closing this, not needed
