### ISSUE TITLE
Add Title and Og to every page

### ISSUE THREAD

**Issue by arpansac** [commudle/commudle-ng#4]
We need to have custom Title and meta data for every page.
This requires the use of **Title** service and **Meta** service.

If you take this issue, post the following in the comments on this issue: 
- Which pages don't have Title and/or Meta tags
- What would you add in the Title and Meta tags. 

Once approved, add them to the code and create a PR!

**Comment by rachitjain1626** [comment]
can i take it?

**Comment by Ashwin-op** [comment]
### Pages which need a title

- _Show repsonses_ of a Form inside an Event's page.


### Pages which might need a change of title

- _New Form_ inside a Community's page can be changed from **New Form** to **New Form | :community_name**
- _Edit Form_ inside a Community's page can be changed from **Edit :form_name Form** to **Edit :form_name Form | :community_name**


Pages which need other meta tags like description, Og-* are the 12 routes in `app-routing-module.ts`. Though I'm not sure if the 404 error page needs a description?


If you can confirm that these are the pages, then I'll start working on the meta content for each page.

**Comment by arpansac** [comment]
> ### Pages which need a title
> * _Show repsonses_ of a Form inside an Event's page.
> 
> ### Pages which might need a change of title
> * _New Form_ inside a Community's page can be changed from **New Form** to **New Form | :community_name**
> * _Edit Form_ inside a Community's page can be changed from **Edit :form_name Form** to **Edit :form_name Form | :community_name**
> 
> Pages which need other meta tags like description, Og-* are the 12 routes in `app-routing-module.ts`. Though I'm not sure if the 404 error page needs a description?
> 
> If you can confirm that these are the pages, then I'll start working on the meta content for each page.



** New Form**: We can do that, the new form page is going to be a common form creation page for some more future entities, example 'surveys'. So the title and meta tag would be dynamic based on the type of parent of the form

**Edit Form**: Same as above

You're going in the right direction!

**Comment by arpansac** [comment]
@Ashwin-op we'll also need to add og:image, in case of community and event pages, it has to be the community logo

**Comment by arpansac** [comment]
Assigning this to myself :)
