### ISSUE TITLE
Show the link to event session page on public event page after the event has concluded

### ISSUE THREAD

**Issue by arpansac** [commudle/commudle-ng#68]
Example:
[https://commudle.com/communities/gdg-new-delhi/events/developer-days-android-day-1](https://commudle.com/communities/gdg-new-delhi/events/developer-days-android-day-1) should have a link to the page where the live session was organized.
This is the link:
[https://commudle.com/communities/gdg-new-delhi/events/developer-days-android-day-1/session](https://commudle.com/communities/gdg-new-delhi/events/developer-days-android-day-1/session)

**Comment by sanchit2107** [comment]
@arpansac Can you Please describe this issue in more detail? So that I can work over it. 

Thanks

**Comment by arpansac** [comment]
Hey @sanchit2107 
If you visit this event page: https://commudle.com/communities/gdg-new-delhi/events/developer-days-android-day-1 
It should have a link to the page where the users can go and view the session which took place in the past, which is on this link: https://commudle.com/communities/gdg-new-delhi/events/developer-days-android-day-1/session

This event is of the type 'single session'.
The multiple session event pages don't have this issue because we display a time table for them.

Let me know if you need screenshots :)

**Comment by sanchit2107** [comment]
Okay, @arpansac I got it. 

You want to say that the event page: https://commudle.com/communities/gdg-new-delhi/events/developer-days-android-day-1 
should be replaced by link through which users can view the past sessions and which is on the link: https://commudle.com/communities/gdg-new-delhi/events/developer-days-android-day-1/session

I hope this is the only one you want to talk about.

If not then please share screenshots.

Thanks .

**Comment by arpansac** [comment]
Just a little bit different, you almost got it. Let me explain with screenshots

EVENT TYPE 1 [DOESN'T NEED ANY CHANGES]: https://commudle.com/communities/gdg-new-delhi/events/developer-days-1-let-s-learn-angular
It has a custom agenda/schedule and even after it gets completed, people can click on the session's link and access the session page. Example image:
![Screenshot 2020-08-23 at 5 33 52 PM](https://user-images.githubusercontent.com/11703424/90977882-da4b1500-e566-11ea-8c34-6dec8cf0fcc5.png)


EVENT TYPE 2 [NEEDS CHANGES]: https://commudle.com/communities/gdg-new-delhi/events/developer-days-android-day-1
This doesn't have a custom agenda, it just has 1 session. But as you can see, there's no way to access that session after the event is completed (this is the link to the session https://commudle.com/communities/gdg-new-delhi/events/developer-days-android-day-1/session).

Here's a description:
![Screenshot 2020-08-23 at 5 39 24 PM](https://user-images.githubusercontent.com/11703424/91292536-4a020f80-e7b4-11ea-9737-bef9a4204d2e.png)

Also, let me help you with some steps:
- Go to projects/commudle-admin/src/app/feature-modules/public-events/components/home-event
- Add an <nb-card> which shows up if the following 2 conditions are met:
  - Event has completed (I have used momentjs in the project)
  - Event does not have a custom agenda (you'll find it easily how to check this)
- The link to any session page is created by appending '/session' to an event which doesn't have a custom agenda

Hope this helps, if not, let me know @sanchit2107 !

Eagerly waiting to see your first successful PR here.

**Comment by arpansac** [comment]
@sanchit2107 are you still interested?

**Comment by sanchit2107** [comment]
Dear @arpansac 

Actually I have my last semester exams this week. So busy in preparation.

I will start working over it after 08-09-2020 if you don't have any problem.

I hope you understand my concern.

**Comment by arpansac** [comment]
Absolutely, just let me know once you begin so that I can assign this issue to you.

**Comment by sanchit2107** [comment]
Sure thank you!!

**Comment by arpansac** [comment]
@sanchit2107 did you fix this and forget to push the PR by any chance? :D

**Comment by arpansac** [comment]
resolved with #98
