### ISSUE TITLE
Facebook Icon not appearing in social handles.

### ISSUE THREAD

**Issue by kpiyush04** [commudle/commudle-ng#70]
While updating my Facebook icon was not working I have attached the screenshot for the reference.

![Screenshot from 2020-08-24 22-26-05](https://user-images.githubusercontent.com/44132300/91073789-2c6c6300-e659-11ea-9792-7c37470c1f8a.png)

**Comment by arpansac** [comment]
Thanks for shifting the issue here @kpiyush04

**Comment by arpansac** [comment]
closed by #78
