### ISSUE TITLE
Redesign agenda timetable

### ISSUE THREAD

**Issue by arpansac** [commudle/commudle-ng#8]
Right now the timetable for an event looks good, supports multiple tracks and locations.

Example: https://commudle.com/communities/gdg-new-delhi/events/devfest-19

But still it looks cramped with all those internal scrolls in each of the sessions. There are 2 tasks associated with this issue:

- Suggest some good but very simple layouts of that section
- Once finalized, code it.

**Comment by Ashwin-op** [comment]
### Idea 1
Instead of showing time every 5 minutes, can we do something like this (**Daily schedule part**)? Here, the first column can be the different topics on which events take place, and first row can be the time in intervals of one hour.

References:
![](https://cdn.dribbble.com/users/2019344/screenshots/6119842/02-a.png)
![](https://i.pinimg.com/originals/c7/24/bb/c724bb50c0ee94049d50c24ddea8a2e8.png)

### Idea 2
Here, the layout is like a card with details on each event.

References:
![](https://cdn.dribbble.com/users/894825/screenshots/4001848/dribbble.jpg)

**Comment by arpansac** [comment]
These are some really cool layouts.
So, the current layout has this hierarchy:
Location > Track > Track Slots (this contains the speaker, topic, timing
details, tags and links)
Plus, people are able to mark some sessions as their favorites too.


Keeping in mind those and also that we need something which is responsive
(mobile friendly), the 2nd one is on the right side, but let's explore more.

**Comment by arpansac** [comment]
@Ashwin-op what do you think about the time table layout on this page: https://gdgx-event.web.app/speakers

**Comment by Ashwin-op** [comment]
It looks clean and elegant!

We can use some coloured background for the same. We can maybe keep a switch button to switch between https://gdgx-event.web.app/schedule and https://gdgx-event.web.app/speakers.

Okay, I'm going too much ahead!

**Comment by arpansac** [comment]
I think we should keep both speakers and schedule on one page. Let's get
the schedule part done. If you're up for it, should I allocate this to you?
Do post the components you'll be needing to make (as in the directory
structure changes) before you start.

**Comment by Ashwin-op** [comment]
Sure!

I think we need two components one for
![image](https://user-images.githubusercontent.com/60032753/83958691-67e56580-a892-11ea-9dba-3fab8f9ab486.png)

and one for
![image](https://user-images.githubusercontent.com/60032753/83958697-77fd4500-a892-11ea-9e00-9e833a8035b0.png)

Also from where do the data for these views come from?

**Comment by arpansac** [comment]
Cool, here's my thoughts:

We have event locations > tracks > track slots

In the existing design also there's only 2 components, one for looping over locations (agenda) and then for tracks and track slots (event-location-tracks)

We could divided the components just as you said:

Locations in tabs (very few events have multiple locations (this could get converted to multiple days in the near future):
<img width="598" alt="Screenshot 2020-06-07 at 1 32 40 PM" src="https://user-images.githubusercontent.com/11703424/83963395-6da76f00-a8c3-11ea-8856-a4943e6aeccb.png">

Each of these rows could be a component. **one edge case, we'll need to group the sessions which might be running in parallel**, by mentioning their track name along side.

Check this small demo I created for the earlier version of Commudle: https://youtu.be/QWOs2KGCJ2A?t=300

I made quite a similar design

**Comment by arpansac** [comment]
Should I assign it to you? @Ashwin-op

**Comment by Ashwin-op** [comment]
Sure!

**Comment by arpansac** [comment]
Any progress? Would love to take a sneak peek into the code

**Comment by arpansac** [comment]
**ROUTINECHECK**
Any progress? @Ashwin-op

**Comment by Ashwin-op** [comment]
Yes, I have made some progress! Will try to get it done by 10 days! 😁
