### ISSUE TITLE
Welcome Hacktoberfest contribution 

### ISSUE THREAD

**Issue by amanintech** [commudle/commudle-ng#81]
I am not a huge fan of this, but do you think accepting #hacktoberfest contribution can boost participation. 

Yes, there would be spams but we can handle it for sure. What's your say @arpansac ?

**Comment by arpansac** [comment]
I've been thinking about it, waiting to reach a point where I can see less
spamming, we'll announce soon!

**Comment by arpansac** [comment]
Added the topic **hacktoberfest** to the repository and also added tags to the issues, all we need is a little word out there :D

**Comment by amanintech** [comment]
Should we make a social media post from the official handles, like a small video and then everyone in core can share it ?

**Comment by arpansac** [comment]
We can!

**Comment by arpansac** [comment]
Done! Thanks for starting this thread :)
