### ISSUE TITLE
Update Nebular to the latest version 6

### ISSUE THREAD

**Issue by arpansac** [commudle/commudle-ng#87]
Finally, there's an update to Nebular, let's do it, it has a Timepicker!

Should be pretty easy I suppose

**Comment by Ashwin-op** [comment]
What are the things that should be updated?

**Comment by arpansac** [comment]
Just the nebular package needs an update for this issue :)

**Comment by Ashwin-op** [comment]
Can we also replace the `ngx-material-timepicker` with the one in Nebular? I'm not sure of how big a change that is but just asking.

**Comment by arpansac** [comment]
Yup, we want to do that, but it would be a separate issue, would require a
little more testing and changes are not just the timepicker but everywhere
time input is taken even in dropdown from the user.

**Comment by Ashwin-op** [comment]
Can you assign this issue to me?

**Comment by arpansac** [comment]
For sure
