### ISSUE TITLE
Use the new nb-timepicker from Nebular

### ISSUE THREAD

**Issue by arpansac** [commudle/commudle-ng#92]
Yay! Nebular has finally added the timepicker to the theme. Looking to use it everywhere there's a schedule mentioned, viz.
- Event create/edit page
- Event custom agenda

**Comment by vinishhub** [comment]
I am vinish I want to contribute to this issue I have installed it locally if you assign me this issue I am new to this event. I have completed my 1 st contribution a week ago.

**Comment by arpansac** [comment]
> I am vinish I want to contribute to this issue I have installed it locally if you assign me this issue I am new to this event. I have completed my 1 st contribution a week ago.

Hey @vinishhub, a Very Happy New Year. 

Assigned the issue to you, just laying the following steps:
- If you can mail at arpan@commudle.com, I will add you as an admin to a demo community
- Once done, please first share which all files will need a change before you proceed with changing the code.

**Comment by arpansac** [comment]
Sent you the invite
