### ISSUE TITLE
Make font-awesome available with nb-icon

### ISSUE THREAD

**Issue by arpansac** [commudle/commudle-ng#93]
Right now, <nb-icon> uses [eva icons](https://akveo.github.io/eva-icons/#/).
However, we also have fontawesome installed as a package, but need to use <fa-icon> everytime. Now, to use font-awesome with nb-icon, some basic changes need to be made. You can easily find it on Google search.

We want it because though eva-icons are amazing, they're very limited.

**Comment by IshetaBansal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by Sloth-Panda** [comment]
I would like to take this. Please let me know.

**Comment by arpansac** [comment]
@IshetaBansal @Sloth-Panda 

Since there's 2 comments on this, let's do it this way, the one who sets up the code first on their system and posts a screenshot here gets this one :)

**Comment by handsome-me** [comment]
is this available?

**Comment by arpansac** [comment]
> is this available?

Yup, very much.
Let me know once you set up the code on your system, I will assign this to you :)

**Comment by handsome-me** [comment]
ohk sir, i'm from codingninjas careercamp learned web dev from you.

**Comment by Sloth-Panda** [comment]
![Screenshot (27)](https://user-images.githubusercontent.com/70213384/103473706-89271980-4dc1-11eb-8e7e-0a8041f7276a.png)


DONE WITH THE SETUP

**Comment by handsome-me** [comment]
@Sloth-Panda are you doing this?i will need some time for setup , so u try till then.

**Comment by Sloth-Panda** [comment]
@handsome-me  Yes, go ahead. I am trying too.

**Comment by arpansac** [comment]
@handsome-me, @Sloth-Panda 
Any luck? This is a simple one.

**Comment by Sloth-Panda** [comment]
sir plz check the slack channel of DWoC have messaged there

**Comment by Amit366** [comment]
Is this issue open??

**Comment by arpansac** [comment]
> Is this issue open??

@Sloth-Panda are you pursuing this actively?

**Comment by Sloth-Panda** [comment]
No  sir, I am not that much looking into it

**Comment by arpansac** [comment]
@Amit366 should I assign this to you?

**Comment by Amit366** [comment]
Yes I would like to work but I don't know Typescript.

**Comment by arpansac** [comment]
@amit, please setup the code on your system first, once you update, I'll assign it to you

> Yes I would like to work but I don't know Typescript.
