### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by tharunc** [commudle/commudle-ng#99]
Hello there,
    I would like to add CODE_OF_CONDUCT.md for this Project. Kindly assign me this issue.

**Comment by arpansac** [comment]
Hi @tharunc 
Can you please elaborate on what would be the points in this doc?

**Comment by tharunc** [comment]
We know code of conduct is a very important thing to be followed when many are contributing in a single project ,
Let me give a description about the code of conduct ,

There will be a pledge which all need to follow so that this community get a harassment-free experience for everyone, regardless of age, body size, disability, ethnicity etc while contributing and we take this pledge to follow the decorum in conversation in issues also.
There will be Standards like :
- Examples of unacceptable behavior by participants
- Examples of behavior that contributes to creating a positive environment
Responsibilities
And if any one faces any issues from other contributors , how to contact ?
Scope of code of conduct like This Code of Conduct applies both within project spaces and in public spaces
These are the things i will be adding , in little more descriptive way
let me know if you can assign me @arpansac

**Comment by arpansac** [comment]
Sounds cool, we did create a Contribution Guidelines doc as well, initially the community part was added into it, but minor. 


Assigning this issue to you.


Are you from DWoC as well? Let me know, I'll add the required tags then.

**Comment by tharunc** [comment]
Thank You. I am from DWOC.
